name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: SimenAsphaug
          template: classic
          base: header, repositories, metadata, habits
          # Enable the languages plugin
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_threshold: 5                       # Limit to top 5 languages
          plugin_languages_details: percentage                # Show usage percentage
          
          # Enable the achievements plugin
          plugin_achievements: yes
          plugin_achievements_display: compact                # Display format: compact
          plugin_achievements_threshold: bronze               # Show achievements starting from bronze level

          # Include organization repositories
          plugin_repositories: yes
          plugin_repositories_affiliations: owner,collaborator,organization_member
