name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Add configuration for the achievements plugin
          plugin_achievements: yes
          plugin_achievements_display: detailed  # Choose from detailed, compact, or advanced
          plugin_achievements_threshold: bronze # Choose threshold: bronze, silver, gold, or platinum
