name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Enable achievements plugin
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_languages: yes
          plugin_languages_affiliations: owner,organization_member
          plugin_languages_sections: most-used,recent
          plugin_languages_indepth: yes
          plugin_repositories_affiliations: owner,collaborator,organization_member
