name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Enable the languages plugin
          plugin_languages: yes
          plugin_languages_sections: most-used,recently-used  # Enable both sections
          plugin_languages_threshold: 5                       # Limit to top 5 languages
          plugin_languages_details: percentage                # Show usage percentage
          plugin_languages_skipped: html,css                  # Exclude HTML and CSS
          plugin_languages_recent_days: 365                   # Analyze recent languages over the past year
          plugin_languages_recent_load: 300                   # Load data from up to 300 repositories
          
          # Include organization repositories
          plugin_repositories: yes
          plugin_repositories_affiliations: owner,collaborator,organization_member
